### PR TITLE
Use JSON.stringify to package updates

### PR DESCRIPTION
**Pull request by rjsmith**
This PR is an attempt to solve the problem of saving update commands into the Transactions collection that contain '$' modifiers, like `$each`, as illustrated in this Jasmine test:

```javascript
   it ('can be updated with $addToSet modifier using $each', function () {
      // SETUP
      var newBars = [{bar: 4}, {bar: 5}];

      // EXECUTE
      tx.start('update foo');
      fooCollection.update(
        {_id: insertedFooDoc._id},
        {
          $addToSet: {
            foo: {$each: newBars}
          }
        },
        {tx: true});
      tx.commit();
      
      // VERIFY
      var fooCursor = fooCollection.find(
        {foo: {bar: 4}});
      expect(fooCursor.count()).toBe(1);      
      var recoveredFoo = fooCursor.fetch()[0];

      // Check transaction
      var txDoc = tx.Transactions.findOne({_id: recoveredFoo.transaction_id});
      expect(txDoc.items.updated[0].update).toEqual({ command: '$addToSet', data: [ { key: 'foo', value: { json: '{"$each":[{"bar":4},{"bar":5}]}' } } ] });
    })
```

It saves objects and arrays as JSON - stringified strings, in a {json: <stringified object>} sub-object, and then uses JSON.parse() if the packaged command value has a `json` field, when unpackaging the serialised command ready for execution.

This *should* work when undo-ing Transaction documents created before this commit (they won't have the `json` sub-object, so will just read it straight out as an object).

This change has been successfully tested in my own meteor-transactions test repo here: https://github.com/rjsmith/meteor-transactions-bug-repo, in particular [this test](https://github.com/rjsmith/meteor-transactions-bug-repo/blob/master/tests/jasmine/server/integration/addToSetEachSpec.js#L102-L127)

### CODE REVIEW

**Comment by rjsmith** [comment]
Related to issue #14

**Comment by rjsmith** [comment]
Added initial testapp for issue #21 including tests covered by this PR

**Comment by JackAdams** [comment]
Thanks, Richard.  This is a pretty significant step in the evolution of this package.

**Comment by JackAdams** [comment]
Okay.  There have been a number of bugfixes and improvements since the last release.  You've backed up most of the changes with tests.  I've done some acceptance testing in my app.  I'm about ready to release a new version.  Thoughts?

**Comment by rjsmith** [comment]
As far as I am concerned, that would be great.  As the MIT license says:

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND ...

**Comment by JackAdams** [comment]
Hahaha... done!

**Pull request merged**
