### PR TITLE
Add tx.allowAutoTransaction config prop

### PR DESCRIPTION
**Pull request by Data-Meister**
By default it's true - preserving the current behavior. If you set it as false, then an error will be thrown if you don't call tx.start() first. 

In our app we always use explicit txns, yet for some reason it sometimes starts committing actions as auto txns. Not sure about the underlying cause of the issue, which happens intermittently when the server is under high load. Either way - when things start going wrong we want to throw an error, not attempting to continue with an auto txn.

### CODE REVIEW

**Comment by JackAdams** [comment]
Good PR. I'll merge and release a new version.

Sorry to hear about the package flaking out under high server load.  It's probably not going to be easy to fix.

**Comment by Data-Meister** [comment]
It might not be an issue with the package per se. I'll monitor the situation and see if we get any more clues. 

This particular server has a lot of its own issues - it regularly drops requests for example, and then retries them not necessarily in the right order.

**Comment by JackAdams** [comment]
Okay. 0.8.6 is published with the PR merged.

**Comment by Data-Meister** [comment]
Awesome :)

**Pull request merged**
