### PR TITLE
Fix bugs and add new Context Setters and Getter

### PR DESCRIPTION
**Pull request by Data-Meister**
FYI: the new setters require Lodash so this is now required by the package. The existing Underscore methods are not effected because _ still equals Underscore. See more notes on that commit.

### CODE REVIEW

**Comment by JackAdams** [comment]
Thank you for this!  I'm crazy busy at the moment but, in a week, I'm going on holiday and will take the chance to merge this, test, release a new version, and start work on a refactor of the internals to make the package more robust.

**Comment by JackAdams** [comment]
I'll probably make `lodash` a weak dependency to keep the package weight down, so that people who want to use the advances context options can do so if they add the `lodash` package themselves.  What does `lodash.merge` do?  I'm only really familiar with the ins and outs of `underscore`.

**Comment by Data-Meister** [comment]
Hi Jack, sorry for the slow reply. 

Here's an illustration of those lodash methods...

_.assign is the same as _.extend in underscore. It overwrites properties. 

    baseObject = { props : { a : 1 }}

    moreProps = { b : 2 }

    _.assign(baseObject, { props: moreProps })
   
    // >> { "props": { "b": 2 } }


_.merge has no equivalent in underscore. It performs a deep merge of properties.  

    baseObject = { props : { a : 1 }}

    moreProps = { b : 2 }

    _.merge(baseObject, { props: moreProps })

    // >> { "props": { "a": 1, "b": 2 } }


I agree it's not a good idea to have both Lodash and Underscore required by the library. Weak dep would be an OK solution, though in my case I'm using lodash from NPM not atmosphere - so it'd still need another extra library. 

Another way could be to remove the advanced context modification methods, and document the fact that getContext() returns a reference to the context which could be modified in place (including using lodash methods). I could make a commit which does this if you like. 

Yet another way would be to migrate the whole library to Lodash. Now I've got used to Lodash it's definitely an improvement compared to underscore, and migrating one of my apps was a good way to learn the (mostly small) differences. But if you're busy right now then it's totally understandable if you're not up for this path.

**Comment by JackAdams** [comment]
I'm pretty sure that `_.extend` in `underscore` does the same as `_.merge` in `lodash`.  This is what I get.
```
a = { b: 123 }
_.extend(a, {c:12})
// >> { b: 123, c: 12 }
```

I have a possible approach that might suit both our purposes:

How about if I test for the existence of the `_.merge` function and use that if it's available (i.e. if the user is using `lodash`), otherwise default to `_.extend`.

Note: the rest of the package uses `underscore` pretty extensively, so I'm not totally confident that replacing `_` with `lodash` will provide a working drop-in replacement.  It might.  I'm open to ideas.  I'll release a version shortly (hopefully within a few hours) with the suggested changes from this PR merged.

**Comment by JackAdams** [comment]
In the end, I opted for a `tx.lodash` that can be set to `tx.lodash = lodash` programatically (e.g. in a `transactionsInit.js` file) if the app has `lodash` installed.  This way the `tx.mergeContext` and `tx.setContextPathValue` functions will work (they rely on `tx.lodash` being set to an actual `lodash` export symbol).

This means that not every app using this package needs both `underscore` and `lodash`, but if an app does happen to have `lodash` installed, the methods are easily available.

**Comment by Data-Meister** [comment]
That's an elegant and pragmatic solution - nice one!

**Pull request merged**
